### ISSUE TITLE
Show Category assigned CMS Block before Easycatalogimg Block

### ISSUE THREAD

**Issue by skazhikadyadya** [tmhub/easycatalogimg#12]
How I can do that? 

I use Porto theme.

Thanks.

**Comment by vovayatsyuk** [comment]
1. [Disable block on categories page](http://docs.swissuplabs.com/m1/extensions/easycatalogimages/#configuration). (But do not disable it globally)
2. Add easycatalogimages [widget](http://docs.swissuplabs.com/m1/extensions/easycatalogimages/#custom-usage) into your cms block.

**Comment by skazhikadyadya** [comment]
Thank you, works perfectly.
